//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public ChiTietHoaDon()
        {
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int idChiTietHD { get; set; }
        public int idHoaDon { get; set; }
        public int idSanPham { get; set; }
        public int soLuong { get; set; }
        public int giaBan { get; set; }
        public string size { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
