//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int idDanhGia { get; set; }
        public Nullable<int> idNguoiDung { get; set; }
        public Nullable<int> idChiTietHD { get; set; }
        public Nullable<int> soSao { get; set; }
        public string noiDung { get; set; }
    
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
