//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int idHoaDon { get; set; }
        public Nullable<int> idNguoiDung { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<int> tongTien { get; set; }
        public string diaChi { get; set; }
        public string hoTen { get; set; }
        public string soDienThoai { get; set; }
        public string email { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
