//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int idSanPham { get; set; }
        public int idDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public int GiaBan { get; set; }
        public HttpPostedFileBase[] HinhAnhFiles { get; set; }
        public string HinhAnh { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
