USE trangsucbac
GO

-- Insert data into Categories table
INSERT INTO DanhMuc (tenDanhMuc, moTa)
VALUES 
('Necklaces', 'Explore our exquisite collection of necklaces crafted with premium materials. From delicate chains to statement pieces, our necklaces are designed to complement any outfit and occasion. Each piece reflects timeless elegance and superior craftsmanship.'),
('Rings', 'Discover our stunning range of rings featuring various designs from classic bands to modern styles. Perfect for engagements, weddings, or everyday wear, our rings are made with high-quality metals and gemstones to last a lifetime.'),
('Earrings', 'Browse through our beautiful selection of earrings including studs, hoops, and dangling designs. Our earrings are hypoallergenic and comfortable to wear all day while adding a touch of sophistication to your look.'),
('Bracelets', 'Adorn your wrist with our elegant bracelet collection. From sleek bangles to charm bracelets, each piece is designed to be versatile and stylish. Perfect for layering or wearing alone as a statement piece.'),
('Wedding Jewelry', 'Our special wedding collection features bridal jewelry that will make your big day even more memorable. From traditional to contemporary designs, these pieces symbolize love and commitment with exceptional quality.');

-- Insert data into Products table
INSERT INTO SanPham (idDanhMuc, TenSanPham, GiaBan, HinhAnh, Size, SoLuong, MoTa)
VALUES 
--- Necklaces
(1, 'Diamond Pendant Necklace', 2500000, '[dchuyen_nho_2.png,dchuyen_nho_4.png,dchuyen3.png, dchuyen2.jpg]', '16,18,20', 15, 
'Crafted for those who appreciate timeless luxury, this diamond pendant necklace showcases a 0.5-carat brilliant-cut diamond with excellent clarity, suspended from a delicate 18K white gold chain. The prong setting maximizes light reflection, creating mesmerizing sparkle from every angle. Ideal for both daytime sophistication and evening glamour, the 16-20 inch adjustable chain allows customizable styling. Each piece undergoes rigorous quality control to ensure the diamond meets GIA standards. The minimalist design pairs effortlessly with other jewelry while making a subtle statement of refined taste. A perfect gift for anniversaries or milestone celebrations, it comes presented in a velvet-lined gift box.'),
(1, 'Pearl Strand Necklace', 1800000, '[pearl-strand1.jpg,pearl-strand2.jpg,pearl-strand3.jpg,pearl-strand4.jpg]', '17,19', 8, 
'Embracing centuries of jewelry tradition, this necklace features 36 perfectly matched AA+ grade freshwater pearls with exquisite luster and minimal surface blemishes. The pearls are hand-knotted on silk thread with 0.5mm spacing for fluid movement and durability, finished with a sterling silver clasp engraved with floral motifs. The 17-19 inch lengths cater to both classic choker and matinee styling preferences. Each pearl is selected for its rosé overtone that complements all skin tones beautifully. This heirloom-quality piece develops a richer patina over time, making it a legacy item to pass through generations. The included pearl care kit ensures lasting beauty.'),
(1, 'Gold Plated Choker', 1200000, '[gold-choker3.jpg,gold-choker1.jpg, gold-choker2.jpg, gold-choker4.jpg]', '14,15,16', 12, 
'This contemporary choker reimagines Renaissance elegance with its 18K gold-plated brass construction and intricate Byzantine-inspired pattern. The flexible yet sturdy design contours comfortably to the neck with a hidden safety chain for added security. Measuring 14-16 inches with three adjustable loops, it accommodates various neck sizes while maintaining its sculptural form. The 3mm width makes a bold statement without being overwhelming, perfect for pairing with plunging necklines or off-shoulder outfits. The hypoallergenic stainless steel base ensures all-day wearability without irritation. A versatile piece that transitions effortlessly from office wear to evening cocktails with its dual matte and polished finishes.'),
(1, 'Silver Moon Charm Necklace', 1500000, '[moon-necklace1.jpg,moon-necklace2.jpeg,moon-necklace3.jpeg,moon-necklace4.jpg]', '16,17,18', 10, 
'Inspired by celestial beauty, this sterling silver (.925) necklace features a crescent moon pendant adorned with seven micro-pave diamonds totaling 0.1 carats. The moon''s surface is hand-engraved with subtle craters and textures for dimensional realism, while the reverse side is polished to a mirror finish. The 16-18 inch box chain is oxidation-treated for enhanced durability and features a spring ring clasp with safety latch. At 2.3cm in diameter, the pendant makes a noticeable yet delicate statement that aligns perfectly with collarbones. The design pays homage to lunar cycles, making it meaningful for birthdays or new beginnings. Comes with a complimentary polishing cloth to maintain its anti-tarnish rhodium plating.'),

-- Rings
(2, 'Solitaire Diamond Ring', 3500000, '[solitaire-ring1.jpg,solitaire-ring2.jpg,solitaire-ring3.jpg,solitaire-ring4.jpg]', '5,6,7,8', 10, 'Representing the pinnacle of engagement ring design, this solitaire features a 0.75-carat round brilliant diamond (G color, VS2 clarity) set in a four-prong platinum head that elevates the stone for maximum brilliance. The knife-edge band tapers from 2mm at the base to 1.5mm at the setting, creating an illusion of greater stone size. Expertly crafted with a comfort-fit interior that feels smooth against the skin for all-day wear. The diamond is ethically sourced with full certification, and the setting allows for easy pairing with wedding bands. Each ring undergoes laser inscription for authenticity and is hand-polished to jewelers mirror finish. Presented in a premium suede ring box with lifetime maintenance guarantee.'),
(2, 'Eternity Band', 2800000, '[eternity-band1.jpg,eternity-band2.jpg,eternity-band3.jpg,eternity-band4.jpg]', '6,7,8,9', 7, 'Symbolizing eternal commitment, this full-eternity band showcases 25 channel-set diamonds (0.25ct total) encircling a 14K white gold band with French back detailing. The continuous diamond row represents unbroken love, while the low-profile setting prevents snagging on fabrics. Expert craftsmen use microscopic precision to secure each stone with invisible tension prongs that enhance the seamless appearance. The 2mm width offers substantial presence without compromising comfort, making it ideal for stacking or standalone wear. The band is rhodium-plated for extra whiteness and scratch resistance. Includes complimentary resizing within the first year and professional cleaning every six months to maintain its perpetual sparkle.'),
(2, 'Stackable Gold Ring Set', 950000, '[stackable-gold-ring1.jpg,stackable-gold-ring2.jpg,stackable-gold-ring3.jpg,stackable-gold-ring4.jpg]', '5,6,7,8', 20,'Designed for creative self-expression, this trio features 14K solid gold rings in three distinct textures: hammered, brushed, and high-polish finishes. Each 1.2mm band is substantial enough for individual wear yet slim enough for comfortable stacking. The set includes sizing guides to mix different finger combinations, from pinky to index fingers. The hammered ring catches light dynamically, while the brushed finish offers understated elegance, and the polished ring adds reflective brilliance. Made with nickel-free gold for sensitive skin, these rings develop a personalized patina over time. The set arrives in a modular box that doubles as a jewelry organizer, perfect for travelers who want to take their signature look anywhere.'),
(2, 'Vintage Sapphire Ring', 1950000, '[sapphire1.jpg,sapphire2.jpg,sapphire3.jpg,sapphire4.png]', '6,7,8', 9, 'Art Deco-inspired ring featuring 0.5ct oval blue sapphire (heated, AA quality) flanked by tapered baguette diamonds in 14K yellow gold. Intricate milgrain detailing on shoulders. Elevated gallery allows band pairing. Perfect for those seeking unique colored gemstone jewelry with vintage charm.'),

-- Earrings
(3, 'Diamond Stud Earrings', 2200000, 'diamond-studs.jpg', 'One Size', 15, 'These quintessential studs feature 0.3-carat round brilliant diamonds (H color, SI1 clarity) set in secure four-prong 14K white gold settings with screw-back closures for added security. The basket setting is engineered to elevate the diamonds closer to the earlobe for enhanced light performance. Each earring is weight-balanced for symmetrical drape and comfort, with medical-grade posts to prevent irritation. The timeless design transitions seamlessly from daytime professional wear to evening glamour. Ideal as first diamond earrings or upgrade pieces, they come with a certificate of authenticity and lifetime tightening service. The diamonds are conflict-free and laser-inscribed for verification.'),
(3, 'Hoop Earrings Set', 750000, 'hoop-set.jpg', 'Small,Medium,Large', 18, 'This versatile trio features 14K gold-plated hoops in three diameters (12mm, 16mm, 20mm) with a uniform 1.3mm thickness for cohesive styling. The hinge-and-latch mechanism ensures secure closure while allowing easy on/off access. The small hoops deliver subtle daytime shine, the medium size works for office-to-evening transitions, and the large hoops make a bold statement for special occasions. Crafted from surgical-grade stainless steel with 5-micron gold plating for lasting wear, they resist tarnishing and fading. The set comes with a velvet organizer to prevent scratching and is perfect for gifting to those who appreciate adaptable jewelry options for every mood and outfit.'),
(3, 'Pearl Drop Earrings', 1350000, 'pearl-drop.jpg', 'One Size', 9, 'Exuding refined elegance, these earrings feature 8mm AAA-grade freshwater pearls suspended from 14K gold-filled chains with delicate ball accents. Each pearl is hand-selected for its perfect spherical shape and luminous pinkish-white hue that flatters all complexions. The 2.5cm chains create graceful movement that elongates the neckline, ideal for updo hairstyles. The fishhook clasps are designed with silicone stoppers for security without compromising ease of wear. These heirloom-quality earrings are packaged with a pearl care guide detailing proper cleaning techniques to preserve their natural luster. Perfect for brides, mothers, or graduates seeking jewelry that matures beautifully with time.'),

-- Bracelets
(4, 'Tennis Bracelet', 3200000, 'tennis-bracelet.jpg', '6,7,8', 6, 'A jewelry box essential, this bracelet features 48 round brilliant diamonds (0.75ct total) set in a flexible 14K white gold link design that drapes elegantly around the wrist. Each diamond is prong-set with microscopic precision to maximize sparkle while ensuring secure stone retention. The patented safety clasp includes two additional safety locks to prevent accidental openings. The 2.3mm width offers substantial presence without being overpowering, suitable for both slender and fuller wrists. Designed to be worn daily, the bracelet undergoes stress-testing to guarantee durability. Includes complimentary annual inspections and rhodium replating services to maintain its like-new brilliance through years of wear.'),
(4, 'Charm Bracelet', 850000, 'charm-bracelet.jpg', '7,8', 14, 'This customizable sterling silver bracelet features a 2mm rolo chain with lobster clasp and five starter charms representing universal symbols (heart, star, key, moon, and sun). The charms are cast from recycled silver using lost-wax technique for intricate detailing, each measuring 7mm for subtle dimension. Additional themed charm collections (birthstones, travel icons, zodiac signs) can be purchased separately to mark life milestones. The bracelet arrives with a personalized engraving tool to add dates or initials to select charms. Designed for layering, the adjustable length accommodates stacking with other bracelets. Packaged in a keepsake box with blank charm tags to document special memories associated with each charm.'),
(4, 'Bangle Set', 1100000, 'bangle-set.jpg', 'One Size', 11, 'Curated for the modern minimalist, this trio includes 18K gold-plated brass bangles in three distinctive designs: a smooth cuff, a twisted rope style, and an engraved geometric pattern. The 6mm width provides visual impact while maintaining wearability for all wrist sizes. The set is engineered with a slight oval shape to prevent spinning during wear and features tension hinges for easy application without clasps. The gold plating undergoes a proprietary 7-layer process for exceptional scratch resistance and long-lasting color depth. Presented in a sustainable bamboo box with anti-tarnish strips, these bangles develop a personalized patina over time that tells the story of your daily adventures.'),

-- Wedding Jewelry
(5, 'Bridal Tiara', 1850000, 'bridal-tiara.jpg', 'One Size', 5, 'This regal tiara features 120 hand-set Swarovski crystals in a graduated design that peaks at 4cm height, creating a flattering frame for the face. The lightweight silver-plated brass base is contoured to fit most head circumferences (22-24 inches) with hidden combs for secure placement under veils. The scrolling vine motif symbolizes growth and new beginnings, with crystal clusters representing the couple''s journey. Adjustable sizing allows customization for different hairstyles from updos to half-up styles. Each crystal is prong-set for maximum sparkle and security, reflecting light beautifully in photographs. The tiara comes with a velvet storage case and specialized cleaning cloth to maintain its bridal radiance for future generations.'),
(5, 'Wedding Band Set', 4200000, 'wedding-band-set.jpg', '6,7,8,9', 8, 'This perfectly matched pair features his-and-hers bands crafted from conflict-free 14K white gold, with the women''s band showcasing 18 micropavé diamonds (0.25ct total) and the men''s band featuring a brushed finish with two diamond accents. The contoured design ensures comfortable year-round wear, with interior polishing to prevent skin irritation. The women''s 2mm band is slightly domed for enhanced durability, while the men''s 4mm band has beveled edges for a modern look. Laser-engraving services are included for personalization with dates, fingerprints, or coordinates. The set arrives in a dual-chambered presentation box with lifetime warranty against manufacturing defects and complimentary annual inspections.'),
(5, 'Bridal Pearl Necklace', 2100000, 'bridal-pearl.jpg', '16,18', 7, 'Specially designed for bridal wear, this necklace features 45 AAA-grade South Sea pearls (7-8mm) interspersed with 2mm round brilliant diamonds in a symmetrical pattern. The platinum clasp is engraved with "Always" in delicate script and functions as the centerpiece of the design. Each pearl is individually knotted for security and fluid movement, with diamond stations adding subtle sparkle against the gown. The 16-18 inch length complements various necklines from sweetheart to portrait styles. The pearls exhibit exceptional orient (rainbow glow) that photographs beautifully under various lighting conditions. Includes a pearl conditioner and storage pouch to maintain the necklace''s luminous quality as a future heirloom piece.');

INSERT INTO NguoiDung (HoTen, Email, SoDienThoai, DiaChi, MatKhau, PhanQuyen)
VALUES 
	(N'Nguyễn Văn Admin', 'admin@trangsucbac.com', '0987654321', N'123 Đường Lê Lợi, Quận 1, TP.HCM', '123456', 'admin'),
	(N'Trần Thị Người Dùng', 'user@example.com', '0912345678', N'456 Đường Nguyễn Huệ, Quận 1, TP.HCM', '123456', 'user');	